services:
  
  postgres:
    image: postgres:16.1
    container_name: medspect-postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=testproject_db
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/