# Generated by Django 4.2.16 on 2024-10-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_inspection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='date',
            new_name='inspection_date',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='title',
            new_name='inspector_name',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='description',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='inspection',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='companies.company'),
            preserve_default=False,
        ),
    ]
