# Generated by Django 4.2.16 on 2024-10-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_text_file_company_aktenzeichen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='notes',
        ),
        migrations.AddField(
            model_name='inspection',
            name='active_substances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='additional_inspectors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='authority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='conclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='critical_errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='findings_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='non_eu_inspection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='other_errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='previous_inspection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='serious_errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='smf_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='team_lead',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
