# Generated by Django 4.2.16 on 2024-10-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_inspection_notes_inspection_active_substances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='non_eu_inspection',
        ),
    ]
