# Generated by Django 4.2.16 on 2024-10-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_inspection_non_eu_inspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='benutzername',
        ),
    ]
