# Generated by Django 4.2.16 on 2024-10-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_company_benutzername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
    ]
