# Generated by Django 4.2.16 on 2024-10-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
