# Generated by Django 4.2.16 on 2024-10-23 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='findings_summary',
        ),
    ]
