# Generated by Django 4.2.16 on 2024-10-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_remove_inspection_findings_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='complaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='contract_testing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='documentation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='other_aspects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='personnel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='production',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='quality_control',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='quality_management',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='samples_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='self_inspection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='site_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='storage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
