# Generated by Django 4.2.16 on 2024-10-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_inspection_complaints_inspection_contract_testing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='aktenzeichen',
            field=models.CharField(default=67833, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', to_field='aktenzeichen'),
        ),
    ]
